# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.define :outer do |web|
    config.vm.network :private_network, ip: "192.168.128.5"
  end

  config.vm.define :inner do |db|
    config.vm.network :private_network, ip: "192.168.128.10"
  end
end
